name: Update Vehicle Templates

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 1,3,5'  # Run at 3:30 UTC on Monday, Wednesday, and Friday
  push:
    branches:
      - master
    paths:
      - 'update_vehicle_templates.py'
      - 'ardupilot_methodic_configurator/vehicle_templates/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update-templates:
    runs-on: windows-latest
    permissions:
      contents: write       # for creating branches and commits
      pull-requests: write  # for creating PRs

    env:
      TEMPLATES_CHANGED: false

    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install dependencies
        # required by update_vehicle_templates.py
        run: |
            uv pip install .[dev]

      - name: Update vehicle templates
        run: python update_vehicle_templates.py

      - name: Check for changes and stage them
        shell: pwsh
        run: |
          git add ardupilot_methodic_configurator/vehicle_templates/**/*.param
          git add ardupilot_methodic_configurator/vehicle_templates/**/*.json
          if ($(git status --porcelain)) {
            "TEMPLATES_CHANGED=true" | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            Write-Host "No changes to commit"
          }
          # Clean untracked (downloaded) apm.pdef.xml files
          git clean -fd ardupilot_methodic_configurator/vehicle_templates/

      - name: Create Pull Request
        if: env.TEMPLATES_CHANGED == 'true'
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          labels: vehicle-templates, automated-pr
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-vehicle-templates
          title: "Update vehicle templates"
          commit-message: "chore(templates): Update vehicle templates with latest parameters"
          body: |
            This PR updates the vehicle templates with the latest parameter definitions.

            Changes were automatically generated by the update_vehicle_templates.py script.
          delete-branch: true
